---

- hosts: all
  become: true
  roles:
   - { role: install_docker, tags: docker} #create directory for the roles
   - { role: install_packages, tags: packages}
   - { role: deploy_docker, tags: deploy_docker}


# # - hosts: all
# #   become: true
# #   roles:
# #    - msql