---

- hosts: all
  become: true
  roles:
   - { role: ping, tags: server}
   - { role: install_docker, tags: docker}
   - { role: install_packages, tags: packages}
   - { role: deploy_docker, tags: deploy_docker}
