---

- hosts: all
  become: true
  roles:
   - { role: docker.yml, tags: docker} #create directory for the roles
   - { role: install_packages.yml, tags: packages}

# # - hosts: all
# #   become: true
# #   roles:
# #    - msql