---
# tasks file for deploy_docker
 - name: copy Docker Compose files
   become: true
   copy:
    src: files/{{ project_dir }}
    dest: ~/

 - name: create wp_volume
   file:
    path: /home/ldes-cou/data/wp_vol
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes

 - name: create db_volume
   file:
    path: /home/ldes-cou/data/db_vol
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes

 - name: Creates env directory
   file:
    path: ~/inception/
    state: directory
   with_items:
   - .env

 - name: Set up .env file
   template:
    src: files/project-env.j2
    dest: ~/inception/.env
 
 # use files parameter to use multiple docker-compose.yml files
 - name: deploy Docker Compose stack
   community.docker.docker_compose:
     project_src: ~/inception/
     files:
     - docker-compose.yml

 - name: launch docker-compose script at reboot
   ansible.builtin.cron:
    name: docker-compose up
    job:
     docker-compose -f {{ compose_prod }} up
    special_time:
     reboot

#  - name: upgrade all packages
#    become: true
#    yum:
#     name: '*'
#     state: latest
#     security: yes