---
# tasks file for docker
    - name: Install docker packages
      remote_user: root
      apt:
       name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
       state: present
       update_cache: yes
      tags:
       - docker

    - name: Add Docker s GPG key for ubuntu from official site
      remote_user: root
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify gpg key with the fingerprint
      remote_user: root
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Configure Docker for ubuntu stable repository
      remote_user: root
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker
    - name: Update apt packages
      remote_user: root
      apt:
        update_cache: yes
      tags:
        - docker
      
    - name: Install docker-ce
      remote_user: root
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker

    # - name: Add "root" user to "docker" group
    #   remote_user: root
    #   user:
    #     name: "root"
    #     group: ""
    #     append: yes
    #   tags:
    #     - docker
    - name: install_docker
      remote_user: root
      pip:
       name: docker
       state: present
       update_cache: yes
      tags: docker

    - name: Install docker-compose from official github repo
      remote_user: root
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'